clearlydefined/operations

.github/workflows/build.yml
tools/integration/lib/harvester.js
tools/integration/test/lib/harvesterTest.js
tools/integration/test/testConfig.js

- Fixed error handling when polling
- Adjust test configuration to avoid timeout.
- Added GitHub Action to run unit tests on tools upon pull and push. An example run can be found [here](https://github.com/qtomlinson/operations/actions/runs/8271676207)
- Added more unit tests to verify api call details, and disable calling dev server during unit tests.

Fix error handling when polling

---

.github/workflows/app-build-and-deploy.yml
.github/workflows/app-build-docker-image.yml
.github/workflows/app-deploy-to-azure.yml
.github/workflows/app-is-deployable.yml

To support dev and prod deploys in the primary apps (i.e. service, crawler, website) and to keep code DRY, this PR moves the existing dev and prod workflows for the service repo to operations.  The two workflows were merged into one deploy process.  Focused steps were split into separate reusable scripts.  The split is primarily to accommodate the need for some repositories to deploy to multiple Azure webapps.
* Passed Secrets:
* AZURE_WEBAPP_PUBLISH_PROFILE: publish profile for the Azure WebApp being deployed
* AZURE_SECONDARY_WEBAPP_PUBLISH_PROFILE: publish profile for a secondary Azure WebApp if being deployed
* Org Secrets:
* AZURE_CREDENTIALS:    service principal that has access to the Azure apps
* DEPLOY_TOKEN:         token that is used to determine if the deployment is allowed
* …

create reusable workflows for prod and dev deploy of primary apps

---

.github/workflows/app-build-and-deploy.yml
.github/workflows/app-build-docker-image.yml
.github/workflows/app-deploy-to-azure.yml

Workflows require a reference that is a branch, tag, or commit.  It is easier to read if a release is created resulting in a release tag.  This is the first release and will be assigned the v1.0.0 tag.  
Considerations: 
* All parts of the reusable workflows will use the same tag. 
* A change to the any of the related workflows will require...
* determine the next version according to semver
* each part of the related reusable workflows will need to be updated to reference each other at the new version
* after merged to main, create a release at the new version
* There are other tools maintained in this repository.  Any of them need to be able to create a release.  No need to update the reusable workflows' version if none of the related workflows are changed.
This PR is setting the …

coordinate reusable workflow by assigning release v1.0.0

---

.github/workflows/app-build-and-deploy.yml
.github/workflows/app-build-docker-image.yml
.github/workflows/app-deploy-to-azure.yml

There was a bug receiving `is-release` as a `boolean`.  Instead of making all callers know they need to pass `'true'` instead of `true`, it is better to move the check here.
This will be made available as tag v1.1.0

move is-release check to reusable workflow

---

.github/workflows/app-build-and-deploy.yml
.github/workflows/app-build-docker-image.yml
.github/workflows/app-deploy-to-azure.yml
.github/workflows/app-is-deployable.yml
.github/workflows/test.yml
scripts/app-workflows/confirm-dev.sh
scripts/app-workflows/determine-image-name.sh
scripts/app-workflows/get-org-id.sh
scripts/app-workflows/get-version.sh
tests/scripts/app-workflows/fixtures/package-lock.json
tests/scripts/app-workflows/test-confirm-dev.bats
tests/scripts/app-workflows/test-determine-image-name.bats
tests/scripts/app-workflows/test-get-org-id.bats
tests/scripts/app-workflows/test-get-version.bats
tests/scripts/app-workflows/test_helpers.bash

Fixes https://github.com/clearlydefined/service/issues/1155
The reusable deploy workflows include scripts to perform some of the steps.  To improve maintainability, these were extracted out to the `scripts/app-workflows` directory with tests in `tests/scripts/app-workflows`.  This change also updates the version of the workflows to `v2.0.0` to reflect the changes.
This also adds a requirement to upload the package-lock.json file to allow get-version to access the version defined in that file.

move workflow scripts to separate file to allow for testing

---

tools/integration/lib/harvester.js
tools/integration/test/integration/e2e-test-service/definitionTest.js
tools/integration/test/integration/fixtures/definitions/pypi-pypi---sdbus-0.12.0.json

A fix has been implemented to correctly parse the LGPL license for certain pypi packages, which is reflected in pull request #518 in the crawler. The production definition was outdated prior to this fix.
The raw harvested result for the package displays the classifier in the registryData as "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)", which was previously parsed as GPL before the fix.
The current dev deployment, reflects the result of this fix: declared: 'GPL-2.0 AND LGPL-2.0-or-later AND LGPL-2.1-or-later":
-  "GPL-2.0" was detected by licensee
- "LGPL-2.0-or-later" was detected by clearlydefined and parsed from the classifier as GNU Lesser General Public License v2 or later (LGPLv2+)
- "LGPL-2.1-or-later" was detected by scancode.
Add the fixture …

Add fixture for pypi package sdbus 0.12.0

---

overview.md

Adds document for new crawler queue env var `CRAWLER_QUEUE_AZURE_CONNECTION_STRING`
Added in PR

Add documentation for new queue connection string env var

---

tools/integration/lib/harvester.js
tools/integration/test/integration/harvestTest.js

Previously, the "always" traversal policy was used to retrigger the harvest of a component. This policy essentially reran all the previously successfully executed tools.  This can be quite cumbersome, especially for integration tests. Sometimes, certain tool results were not available, such as when the schema version had been updated, causing the previously harvested results to become stale and the tool results with the newly updated schema version to be missing.  When the tool result for a specific component is missing, using the "always" policy leads to a "Unreachable for reprocessing " status and the tool being skipped.
To address this issue in integration testing, the approach was to first trigger a round of harvest using the default traversal policy. With the default policy, the …

Use the new traversal policy to simplify reharvest

---

tools/blobstorage-backupdata/BackupData.csproj
tools/blobstorage-backupdata/BackupJob.cs
tools/blobstorage-backupdata/Dockerfile
tools/blobstorage-backupdata/Program.cs

This change mainly reduces the CosmosDB batch size to get rid of the exception mentioned in the #95. The other changes here are upgrades, such as moving to current .NET LTS. 
As a small convenience addition, `DotNetEnv.Env.Load()` allows running the program locally with a `.env` file.

Fix https://github.com/clearlydefined/operations/issues/95

---

.github/workflows/app-build-and-deploy.yml
.github/workflows/app-build-docker-image.yml
.github/workflows/app-deploy-to-azure.yml
.github/workflows/app-is-deployable.yml

This sets up the docker image to hold the version and sha that are used to verify which version is actually running.  The previous approach used Azure configs that get set just before the deploy.  If the deploy were to fail, those configs stay the same leading to a false report on the version and sha.
* https://github.com/clearlydefined/service/pull/1199
* https://github.com/clearlydefined/crawler/pull/574
* add status check with version and sha to website
* consider using a different endpoint (e.g. status-check) for all 3 major apps because the website will not be able to use `/` because that goes to a page that already has content (i.e. homepage)
* after this PR is merged
* update the version in all `app_` workflows and release
* update workflows using the operations `app_` workflows to …

add version and sha in docker image instead of Azure configs

---

.github/workflows/app-build-and-deploy.yml
.github/workflows/app-build-docker-image.yml
.github/workflows/app-is-deployable.yml
scripts/app-workflows/determine-image-name.sh
tests/scripts/app-workflows/test-determine-image-name.bats

To migrate deployment of Production Crawler to CD Azure from Microsoft owned Azure.
Changes to workflow `app-build-and-deploy`
This PR enables the optional docker image publish to Docker Hub, conditional on providing
- Input `docker-hub-username` 
- secret `DOCKERHUB_TOKEN`
Without these the action only deploys to ghcr
- Unlocks ability to have production crawlers in Cd Azure means any member of Clearly Defined with access to the account can manage, support and troubleshoot. Currently we need to request help from MSFT if there are any issues.
- Our other App Services the api and website are already using ghcr for images so we need to move crawler there as well
- MSFT crawlers are deployed using webhook from dockerhub that triggers the deploy. So we still need to publish to dockerhub. …

Deploy image to docker optionally, as well as GHCR

---

.github/workflows/integration-test.yml

So that we can control Integration tests.
Choose to run with dynamic fixtures, fixed fixtures, or both

Control integration tests with input

---

.github/workflows/integration-test.yml

https://github.com/clearlydefined/operations/pull/102 has broken the integration test action logic. This change is to restore it, while still keeping the flavour of integration tests to run user-configurable.

Use user input to drive integration tests action

---

tools/integration/test/integration/e2e-test-service/definitionTest.js

The production definition (expected) for npm/npmjs/-/redis/0.1.0 does not include the declared license. The definition computed on the dev deployment (with ScanCode v32 update) contains the declared license. Ensure that license.declared is always compared, even if the field is missing from the expected result.

Ensure license.declared is always compared

---

tools/integration/test/integration/e2e-test-service/attachmentTest.js
tools/integration/test/integration/e2e-test-service/definitionTest.js
tools/integration/test/integration/e2e-test-service/noticeTest.js

Integration tests running over a list of components are being skipped.  The reason is that the callbacks in `describe()` must be synchronous.  See documentation at https://github.com/mochajs/mocha/pull/5046/files and detailed explanation at https://github.com/mochajs/mocha/issues/2975#issuecomment-1004176440.
Adapted the affected tests accordingly. Changes are mainly wrapping the mocha describe into a top level async function. 
The log of a test run can be found [here](https://github.com/qtomlinson/operations/actions/runs/11535407563/job/32110446531).

Fix integration tests

---

.github/workflows/app-build-docker-image.yml
scripts/app-workflows/determine-image-name.sh
tests/scripts/app-workflows/test-determine-image-name.bats

Fix the crawler prod image not updating on deploy.  This was caused by the current production crawlers use of the latest tag in Docker Hub to get the image to use and the deploy process through GH workflow not creating that tag.
On release of crawler prod, the deploy should update the production crawlers to the new release version.
On release of crawler prod, the deploy has no effect on the production crawlers.
Update the GH workflow process to create the `latest` tag in Docker Hub. The prod crawlers will be triggered to grab the new latest image and restart.
* in test branch, updated crawler-dev deploy to add docker credentials to my docker hub
* ran deploy dev on the test branch
* confirmed that the version and latest tags were created in my docker hub
Update refs to this workflow to a …

for docker hub image, include latest tag

---

.github/workflows/integration-test-custom.yml
.github/workflows/integration-test.yml
tools/integration/test/integration/testConfig.js

Run definition tests in integration testing on the custom infra structure.
Also add the option of skipping harvest for static components as the harvest can take quite some time.

Run the entire end to end test suite in integration test

---

tools/integration/lib/fetch.js
tools/integration/test/integration/e2e-test-service/originsTest.js
tools/integration/test/integration/testConfig.js

This pull request introduces a new test case file named `originsTest.js`, designed to expand test coverage for the Origins API in the service repository. The test case validates the API responses by calling the Origins API with all coordinates specified in the `testConfig.js` file. It compares responses across two environments to ensure no regression test cases fail, thereby increasing our confidence in the new source code introduced.
- **File Added**: `originsTest.js`
- **Purpose**: To test and validate the Origins API against coordinates in `testConfig.js`.
- **Validation**: API responses are compared between two environments dev and prod to check for consistency and detect any regressions.
Testing of this test case file is completed
Issue - …

Add Test Case for Origins API

---

tools/integration/test/integration/e2e-test-service/originsTest.js

This pull request refactors the `originsTest.js` file to enhance efficiency and reliability due to discrepancies in API responses between production and development environments.
1. **Logic Improvement**:
- Replaced strict equality checks with validation ensuring non-empty responses.
- Confirmed keyword presence in packages and correct revision versioning.
2. **Function Renaming**:
- `compareEndpoints` to `validateEndpointResponses`.
- `compareOriginsWithRevisions` to `validateEndpointWithRevisions`.
- `compareOrigins` to `validateOriginResponses`.
- `getProviderType` to `resolveProviderType`.
3. **Code Structure**:
- New utility functions: `assertPackageResponse`, `assertRevisionResponse`, `normalizeVersion`.
- Improved response assertions and clarified test case labels.

Refactor of Origins API Tests for Improved Robustness and Efficiency

---

.github/workflows/integration-test.yml

The log for the abbreviated run is available at https://github.com/qtomlinson/operations/actions/runs/14767228124/job/41460965345. This run, triggered by a push event, executes the definition tests for only two components

Configure scheduled execution for end-to-end integration test suite

---

.github/workflows/integration-test.yml
tools/integration/lib/cleanupPR.js
tools/integration/package-lock.json
tools/integration/package.json
tools/integration/test/integration/cleanup.js
tools/integration/test/integration/e2e-test-service/curationTest.js
tools/integration/test/integration/testConfig.js

Our integration tests create a curation pull request (PR), which need to be cleaned up, especially if the tests are to be run regularly. This PR implements a cleanup step for the integration test suite, including closing test curation pull requests generated during the tests.
A successful cleanup log can be found under `Clean up`:
https://github.com/qtomlinson/operations/actions/runs/14918054187/job/41907933077
**Future work:**
- Check whether the improved integration tests on infrastructure need to be updated as well.

Add cleanup for integration tests

---

service_config/crawler.md

..as a follow-up to https://github.com/clearlydefined/crawler/pull/641.

Add docs for `CRAWLER_LICENSEE_PARALLELISM`

---

tools/integration/test/integration/fixtures/definitions/nuget-nuget---NuGet.Protocol-6.7.1.json

This pull request resolves a recently failing integration test:  
[GitHub Actions Run](https://github.com/clearlydefined/operations/actions/runs/15086531720/job/42409765031)
The failure was caused by a mismatch in the license file's hash values between the expected and actual outputs.
**Expected Output:**  
```json
{
"path": "clearlydefined/downloaded/LICENSE",
"license": "Apache-2.0 AND (ECL-2.0 AND Apache-2.0)",
"hashes": {
"sha1": "6215cb16583ad28f22e1a7c905ee5bbee1044635",
"sha256": "e38b0854f4b591f3297571e73c665bd4266e8c8f9c55fb580942e51a4da619a8"
},
"token": "e38b0854f4b591f3297571e73c665bd4266e8c8f9c55fb580942e51a4da619a8"
}
```
**Actual Output:**  
```json
{
"path": "clearlydefined/downloaded/LICENSE",
"license": "Apache-2.0 AND (ECL-2.0 AND Apache-2.0)",
"hashes": {
"sha1": …
```

Update the license file hashes in the fixture for NuGet.Protocol/6.7.1

---

release-management.md

The use of Azure DevOps is no longer needed for the crawler production deploy.  The GitHub workflow for production release publishes the Docker image to ghcr.io package and Docker Hub.
There is an extra step required.  The prod crawlers are not automatically restarting when there is a new image.  I believe they used to, but don't seem to be happening now.
I've asked @mpcen to restart the crawler and how MSFT would like this to happen in the furture.  Ideally, the restart would be initiated from the deploy workflow that generates and publishes the production images.

Refine crawler production deploy description

---

.github/workflows/integration-test.yml

- Enable manual execution of integration tests for development quality checks.
- Restrict scheduled tests to run only on clearlydefined/operations.

Redo check to run integration test

---

tools/integration/test/integration/testConfig.js

During our CI runs, the Debian test case for mini-httpd/1.30-0.2 has been failing.
See the failing workflow:
https://github.com/clearlydefined/operations/actions/runs/16382766911/job/46297303976
Debian: got 0 entries for cd:/debsrc/debian/-/mini-httpd/1.30-0.2
The version (1.30-0.2) for mini-httpd used in our test suite is no longer available in the Debian package repo.
See: http://ftp.debian.org/debian/pool/main/m/mini-httpd/
**### Resolution**
There are newer versions (e.g., 1.30-2 and above) available. This PR updates the test config to use a currently available version to restore CI pass (successful harvest).
**### Checklist**

Fix failing Debian test case for mini-httpd
